---
- include: ceph.yml
  when:
    - (enable_ceph | bool) and (glance_backend_ceph | bool)
    - inventory_hostname in groups['ceph-mon'] or
      inventory_hostname in groups['glance-api'] or
      inventory_hostname in groups['glance-registry']

- include: external_ceph.yml
  when:
    - (enable_ceph | bool == False) and (glance_backend_ceph | bool)
    - inventory_hostname in groups['glance-api'] or
      inventory_hostname in groups['glance-registry']

- include: register.yml
  when: inventory_hostname in groups['glance-api']

- include: config.yml
  when: inventory_hostname in groups['glance-api'] or
        inventory_hostname in groups['glance-registry']

- include: bootstrap.yml
  when: inventory_hostname in groups['glance-api']

- name: Choosing host for glance_api if using file backend
  set_fact:
    glance_api_hosts: "{{ groups['glance-api']|first }}"
  when:
    - glance_backend_file | bool

- name: Choosing hosts for glance_api if using shared storage
  set_fact:
    glance_api_hosts: "{{ groups['glance-api'] }}"
  when:
    - glance_backend_file | bool == False

- name: Flush handlers
  meta: flush_handlers

- include: check.yml
  when: inventory_hostname in groups['glance-api'] or
        inventory_hostname in groups['glance-registry']
