---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "{{ project_name }}"

- name: Copying over config.json files for services
  template:
    src: "rabbitmq.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "{{ project_name }}"

- name: Copying over rabbitmq configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ node_config_directory }}/{{ project_name }}/{{ item }}"
  with_items:
     - "rabbitmq-env.conf"
     - "rabbitmq.config"
     - "rabbitmq-clusterer.config"
     - "definitions.json"
