---
- name: Starting rabbitmq container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ rabbitmq_image_full }}"
    name: "{{ project_name }}"
    volumes:
      - "{{ node_config_directory }}/{{ project_name }}/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ project_name }}:/var/lib/rabbitmq/"
      - "kolla_logs:/var/log/kolla/"
